### ISSUE TITLE
Update versions in requirements.yml

### ISSUE THREAD

**Issue by sasanikolic90** [geerlingguy/drupal-pi#14]
Currently, the Ansible script is failing on the step to "Ensure PHP packages are installed" with the error message `No package matching 'php7.0-common' is available`. 
This is happening because currently there are some big changes being made to use PHP's build from source option and PHP7 is being set by default.

To solve this, the `requirements.yml` needs to be updated to include the latest versions as follows:

```

---
- src: geerlingguy.composer
  version: 1.4.0
- src: geerlingguy.drush
  version: 1.1.2
- src: geerlingguy.firewall
  version: 1.0.9
- src: geerlingguy.git
  version: 1.1.1
- src: geerlingguy.mysql
  version: 2.2.1
- src: geerlingguy.nginx
  version: 1.9.2
- src: geerlingguy.php
  version: 2.0.3
- src: geerlingguy.php-mysql
  version: 1.2.0
- src: geerlingguy.security
  version: 1.2.0
```

**Comment by CyberGrinch** [comment]
The following packages have unmet dependencies:", " php-common : Breaks: php-apcu (< 5.1.3+4.0.10-2~) but 5.1.3+4.0.10-1~bpo8+1 is to be installed

**Comment by geerlingguy** [comment]
There are actually a few different things that are broken currently with the way it's set up. I'm first going to add some tests to make sure I can have a quicker turnaround time than building everything directly on the pi!

**Comment by geerlingguy** [comment]
See notes in https://github.com/geerlingguy/drupal-pi/pull/15
