### ISSUE TITLE
'ansible_ssh_user' is undefined

### ISSUE THREAD

**Issue by bhasselbeck** [geerlingguy/drupal-pi#17]
When running the ansible task to add Drupal cron.  Message output below...

``` bash
ASK [Add Drupal cron job.] ****************************************************
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "'ansible_ssh_user' is undefined"}
```

**Comment by bhasselbeck** [comment]
Looks like Ansible has deprecated deprecated the “ssh” from ansible_ssh_user, ansible_ssh_host, and ansible_ssh_port to become ansible_user, ansible_host, and ansible_port.

**Comment by bhasselbeck** [comment]
You can fix this by adding the `--user=pi` flag to the `ansible-playbook -i inventory -c local main.yml` command
```bash
$ ansible-playbook -i inventory -c local main.yml --user=pi
```

**Comment by geerlingguy** [comment]
I forgot to mention, this was fixed in https://github.com/geerlingguy/drupal-pi/commit/5aef08bd4ba51c92ce4914a03122187b9b64b032 - thanks for reporting it!
