### ISSUE TITLE
TASK [Install Drupal dependencies with Composer.]

### ISSUE THREAD

**Issue by jimenega** [geerlingguy/drupal-pi#19]
Please help.  I seem to get almost to the end of the process but I keep getting this fatal error.
I have tried this with 2017-03-02-raspbian-jessie.img  and with the lite version and they both give me the same result.  I'am reading up on Composer but I am not familiar with it.  Should there be a composer.json file in `/var/www/drupal` (?)  The following is the error I receive.

```
TASK [Install Drupal dependencies with Composer.] ******************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": ["composer", "install"], "delta": "0:00:00.364124", "end": "2017-03-08 17: 37:20.531550", "failed": true, "rc": 1, "start": "2017-03-08 17:37:20.167426", "stderr": "Do not run Composer as root/super user! See https://getcomposer.org/root for details\nComposer could not find a composer.json file in /var/www/drupal\nTo initialize a project, please create a composer.json file as described in the https://getcomposer.org/ \"Getting Started\" section", "stdout": "",                                         "stdout_lines": [], "warnings": []}
RUNNING HANDLER [geerlingguy.nginx : restart nginx] ****************************
RUNNING HANDLER [geerlingguy.php : restart webserver] **************************
RUNNING HANDLER [geerlingguy.php : restart php-fpm] ****************************
RUNNING HANDLER [geerlingguy.security : restart ssh] ***************************
        to retry, use: --limit @/home/pi/drupal-pi/main.retry
PLAY RECAP *********************************************************************
127.0.0.1                  : ok=107  changed=27   unreachable=0    failed=1
```

**Comment by geerlingguy** [comment]
@jimenega - Can you give a full log (e.g. go to gist.github.com and create a new gist containing the full log output) so I can see what else is happening?

If you're using the drupal.make.yml Drush make file with Drupal 8, then there should be a `composer.json` file in the Drupal document root, and it would then be run by Ansible.

One possibility is if you're using Drupal 7 instead of Drupal 8, this file would not exist.

Can you provide your `config.yml` file as well?

**Comment by jimenega** [comment]
I am using Drupal 8.
I will provide requested info early next week as I am on travel and don't
have access to logs at this time.

Thanks
jimenega

**Comment by jimenega** [comment]
I re-installed the entire project and was able to get drupal-pi working perfectly. 
Maybe I did not use sudo when running ansible-playbook.

**Comment by geerlingguy** [comment]
@jimenega - Great! Glad you could get it working finally :)
