### ISSUE TITLE
Error running playbook

### ISSUE THREAD

**Issue by crockerrd** [geerlingguy/drupal-pi#24]
I just wanted to report that I'm getting the following error:

_ERROR: become is not a legal parameter at this level in an Ansible Playbook_

I get it immediatley after running the command `ansible-playbook -i inventory -c local main.yml`

Any suggestions?

**Comment by geerlingguy** [comment]
@crockerrd - That usually means you're running an older version of Ansible. Check with `ansible --version`. You should use at least Ansible 2.0, if not 2.2 or later (recommended).

**Comment by EPrograming** [comment]
@geerlingguy  I am getting a similar error:
ERROR! the role 'geerlingguy.firewall' was not found in /home//drupal-pi/roles:/home/drupal-pi/roles:/home/drupal-pi
I got it immediately after running the command ansible-playbook -i inventory -c local main.yml
Any suggestions on how to fix?

**Comment by geerlingguy** [comment]
@EPrograming - Please see https://github.com/geerlingguy/drupal-pi/issues/26

Closing this issue since there's been no response and I think it should be resolved by now.
