### ISSUE TITLE
Automatically redirects to www.drupalpi.dev

### ISSUE THREAD

**Issue by ghost** [geerlingguy/drupal-pi#25]
I'm sorry, I don't know how to disable this.
When I access my webserver by ip address or localhost, I get redirected to www.drupalpi.dev
Anyone know how to stop this?

**Comment by geerlingguy** [comment]
This is part of the configuration:

```
drupal_site_canonical_uri: "www.drupalpi.test"
drupal_site_redirect_uri: "drupalpi.test"
```

If you need to use only the IP, try using the IP as the canonical URI. Otherwise use a URI like the new default, `www.drupalpi.test`, then make sure to add an entry for it in your hosts file.

The redirect URI will redirect that to the canonical URI.
