### ISSUE TITLE
geerlingguy.firewall error when running playbook

### ISSUE THREAD

**Issue by EPrograming** [geerlingguy/drupal-pi#26]
ERROR! the role 'geerlingguy.firewall' was not found in /home//drupal-pi/roles:/home/drupal-pi/roles:/home/drupal-pi
I got it immediately after running the command ansible-playbook -i inventory -c local main.yml

Made a new issue for this becouse it is a different error.

Any suggestions on how to fix?

**Comment by geerlingguy** [comment]
You first need to run the command: `ansible-galaxy install -r requirements.yml` as outlined in the README file. Make sure to run it inside the drupal-pi directory.
