### ISSUE TITLE
Ansible installation instructions in README require extra libffi packages

### ISSUE THREAD

**Issue by betz** [geerlingguy/drupal-pi#27]
Hey,

I'm following the readme, but i am bumping on different issues:

* Installing ansible got issues missing package. 
** Fixed with a 'apt-get install libffi libffi-dev'.
* when running ansible, got the message it couldn't a package named php5.
** changed php5 to 7.0 (note 7.0, not just 7)
* now i have an issue when 'Drupal site with drush makefile':  "Unable to clone drupal from http://git.drupal.org/project/drupal.git"
** didn't look into this one yet

Cheers,
tom

**Comment by geerlingguy** [comment]
For the 2nd issue, moving that work to #29.

For the first issue, that's something that may or may not be required depending on the version of raspbian lite... and it can be quite annoying :P I'm going to change this issue into just dealing with that.

For the third issue, that sounds like maybe a temporary git problem, or a Drush version problem or something.

**Comment by geerlingguy** [comment]
I'm re-testing on a fresh raspbian install today using Raspbian based on Debian 9 (latest as of March 2018).

**Comment by geerlingguy** [comment]
Test process:

  1. Followed these directions: https://github.com/geerlingguy/drupal-pi#set-up-on-raspberry-pi-with-raspbian-lite--cli
  2. Got the following error:

```
    No package 'libffi' found
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
```

**Comment by geerlingguy** [comment]
It looks like we just need to add in `libffi-dev` to the list of apt packages to install. Testing that now.

**Comment by geerlingguy** [comment]
Worked! And now:

```
pi@raspberrypi:~ $ ansible --version
ansible 2.5.0
  config file = None
  configured module search path = [u'/home/pi/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

Also, one part took a bit longer than the rest: https://github.com/pysam-developers/pysam/issues/184

**Comment by betz** [comment]
thanks
