### ISSUE TITLE
No package matching php7.0-apcu

### ISSUE THREAD

**Issue by Trixanna** [geerlingguy/drupal-pi#32]
I tired to install drupal using this repository and ansible-playbook but the php install portion failed with "No package matching 'php7.0-apcu' is available".

When looking through apt-get i found a php-apc but no php7.0-apcu. I tired changing to the 'php-apc' in Debian.yml however the script seems to check for php7.0-apcu instead of php-apc. Not really sure how to fix this myself.

Thanks

**Comment by geerlingguy** [comment]
Yikes! Sorry about that; I'll try to get around to testing this again soon. I haven't had to build a new Drupal Pi for a few months and I've been out sick for a while, so it could be a little time before I can fully test a fix on a Pi.

**Comment by geerlingguy** [comment]
@Trixanna - I have changed the way this project works quite a bit, especially in #21 — please try wiping your microSD card and re-imaging it with the latest Raspbian Stretch image, and running through the installation steps in the README again. It should be a little more robust now, and hopefully you won't encounter any errors!

I just had to rebuild my little solitary Pi 2 to allow it to serve www.pidramble.com while my Pi Dramble cluster is on vacation, and everything in the latest version of this project seems to work well now.
