### ISSUE TITLE
Issue at end of build with php.

### ISSUE THREAD

**Issue by boilermanc** [geerlingguy/drupal-pi#33]
hey jeff, thanks for putting this all together! Trying to setup a pi to test a drupal app.  I get to the end and get this error.

`TASK [geerlingguy.php : Ensure PHP packages are installed.] ***********************************************
fatal: [127.0.0.1]: FAILED! => {
    "cache_update_time": 1542924453,
    "cache_updated": false,
    "changed": false,
    "rc": 100
}

STDOUT:

Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  libargon2-1 libsodium23
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  autoconf automake autotools-dev libc-client2007e libltdl7 libmcrypt4
  libpcre16-3 libpcre3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libssl-dev
  libssl1.1 libtool libyaml-0-2 mlock php7.1-readline shtool
Suggested packages:
  autoconf-archive gnu-standards autoconf-doc gettext uw-mailutils
  libmcrypt-dev mcrypt libssl-doc libtool-doc gfortran | fortran95-compiler
  gcj-jdk php-pear dh-php
Recommended packages:
  libltdl-dev php-apcu-bc pkg-php-tools
The following NEW packages will be installed:
  autoconf automake autotools-dev libc-client2007e libltdl7 libmcrypt4
  libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libssl-dev libtool
  libyaml-0-2 mlock php-apcu php-yaml php7.1 php7.1-cli php7.1-common
  php7.1-curl php7.1-dev php7.1-fpm php7.1-gd php7.1-imap php7.1-json
  php7.1-mbstring php7.1-mcrypt php7.1-opcache php7.1-readline php7.1-sqlite3
  php7.1-xml shtool
The following packages will be upgraded:
  libpcre3 libssl1.1
2 upgraded, 32 newly installed, 0 to remove and 3 not upgraded.
Need to get 11.6 MB of archives.
After this operation, 33.3 MB of additional disk space will be used.
Get:1 http://mirror.umd.edu/raspbian/raspbian stretch/main armhf autoconf all 2.69-10 [338 kB]
Get:2 http://mirror.umd.edu/raspbian/raspbian stretch/main armhf autotools-dev all 20161112.1 [73.4 kB]
Get:3 http://mirror.umd.edu/raspbian/raspbian stretch/main armhf automake all 1:1.15-6 [733 kB]
Get:4 http://mirror.umd.edu/raspbian/raspbian stretch/main armhf mlock armhf 8:2007f~dfsg-5 [34.4 kB]
Get:5 http://mirror.umd.edu/raspbian/raspbian stretch/main armhf libc-client2007e armhf 8:2007f~dfsg-5 [561 kB]
Get:6 http://mirror.umd.edu/raspbian/raspbian stretch/main armhf libltdl7 armhf 2.4.6-2 [386 kB]
Get:7 http://mirror.umd.edu/raspbian/raspbian stretch/main armhf libmcrypt4 armhf 2.5.8-3.3 [64.2 kB]
Get:8 http://mirror.umd.edu/raspbian/raspbian stretch/main armhf libtool all 2.4.6-2 [545 kB]
Get:9 http://mirror.umd.edu/raspbian/raspbian stretch/main armhf libyaml-0-2 armhf 0.1.7-2 [39.9 kB]
Get:10 http://mirror.umd.edu/raspbian/raspbian stretch/main armhf shtool all 2.0.8-9 [134 kB]
Get:11 https://packages.sury.org/php stretch/main armhf libpcre3 armhf 2:8.41-1+0~20180928072106.2+stretch~1.gbp97d153 [320 kB]
Get:12 https://packages.sury.org/php stretch/main armhf libssl1.1 armhf 1.1.1-2+0~20181105132527.5+stretch~1.gbp90eb86 [1310 kB]
Get:13 https://packages.sury.org/php stretch/main armhf libpcre16-3 armhf 2:8.41-1+0~20180928072106.2+stretch~1.gbp97d153 [242 kB]
Get:14 https://packages.sury.org/php stretch/main armhf libpcre32-3 armhf 2:8.41-1+0~20180928072106.2+stretch~1.gbp97d153 [234 kB]
Get:15 https://packages.sury.org/php stretch/main armhf libpcrecpp0v5 armhf 2:8.41-1+0~20180928072106.2+stretch~1.gbp97d153 [150 kB]
Get:16 https://packages.sury.org/php stretch/main armhf libpcre3-dev armhf 2:8.41-1+0~20180928072106.2+stretch~1.gbp97d153 [590 kB]
Get:17 https://packages.sury.org/php stretch/main armhf libssl-dev armhf 1.1.1-2+0~20181105132527.5+stretch~1.gbp90eb86 [1600 kB]
Get:18 https://packages.sury.org/php stretch/main armhf php7.1-common armhf 7.1.24-1+0~20181112093455.10+stretch~1.gbp09a4fd [490 kB]
Get:19 https://packages.sury.org/php stretch/main armhf php7.1-json armhf 7.1.24-1+0~20181112093455.10+stretch~1.gbp09a4fd [15.5 kB]
Get:20 https://packages.sury.org/php stretch/main armhf php7.1-opcache armhf 7.1.24-1+0~20181112093455.10+stretch~1.gbp09a4fd [125 kB]
Get:21 https://packages.sury.org/php stretch/main armhf php7.1-readline armhf 7.1.24-1+0~20181112093455.10+stretch~1.gbp09a4fd [10.8 kB]
Get:22 https://packages.sury.org/php stretch/main armhf php7.1-cli armhf 7.1.24-1+0~20181112093455.10+stretch~1.gbp09a4fd [1134 kB]
Get:23 https://packages.sury.org/php stretch/main armhf php7.1-fpm armhf 7.1.24-1+0~20181112093455.10+stretch~1.gbp09a4fd [1139 kB]
Get:24 https://packages.sury.org/php stretch/main armhf php-apcu armhf 5.1.12+4.0.11-2+0~20181105174317.7+stretch~1.gbp8d5801 [85.4 kB]
Get:25 https://packages.sury.org/php stretch/main armhf php-yaml armhf 2.0.2+1.3.1-3+0~20181003090730.2+stretch~1.gbp63ff1d [31.8 kB]
Get:26 https://packages.sury.org/php stretch/main armhf php7.1 all 7.1.24-1+0~20181112093455.10+stretch~1.gbp09a4fd [60.7 kB]
Get:27 https://packages.sury.org/php stretch/main armhf php7.1-curl armhf 7.1.24-1+0~20181112093455.10+stretch~1.gbp09a4fd [25.2 kB]
Get:28 https://packages.sury.org/php stretch/main armhf php7.1-dev armhf 7.1.24-1+0~20181112093455.10+stretch~1.gbp09a4fd [532 kB]
Get:29 https://packages.sury.org/php stretch/main armhf php7.1-gd armhf 7.1.24-1+0~20181112093455.10+stretch~1.gbp09a4fd [22.3 kB]
Get:30 https://packages.sury.org/php stretch/main armhf php7.1-imap armhf 7.1.24-1+0~20181112093455.10+stretch~1.gbp09a4fd [25.1 kB]
Get:31 https://packages.sury.org/php stretch/main armhf php7.1-mbstring armhf 7.1.24-1+0~20181112093455.10+stretch~1.gbp09a4fd [417 kB]
Get:32 https://packages.sury.org/php stretch/main armhf php7.1-mcrypt armhf 7.1.24-1+0~20181112093455.10+stretch~1.gbp09a4fd [12.8 kB]
Get:33 https://packages.sury.org/php stretch/main armhf php7.1-sqlite3 armhf 7.1.24-1+0~20181112093455.10+stretch~1.gbp09a4fd [20.8 kB]
Get:34 https://packages.sury.org/php stretch/main armhf php7.1-xml armhf 7.1.24-1+0~20181112093455.10+stretch~1.gbp09a4fd [90.0 kB]
apt-listchanges: Reading changelogs...
Preconfiguring packages ...
Fetched 11.6 MB in 20s (555 kB/s)
(Reading database ... 39294 files and directories currently installed.)
Preparing to unpack .../libpcre3_2%3a8.41-1+0~20180928072106.2+stretch~1.gbp97d153_armhf.deb ...
Unpacking libpcre3:armhf (2:8.41-1+0~20180928072106.2+stretch~1.gbp97d153) over (2:8.39-3) ...

STDERR:

Extracting templates from packages: 100%
E: Sub-process /usr/bin/dpkg exited unexpectedly

MSG:

'/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"     install 'php7.1' 'php7.1-apcu' 'php7.1-cli' 'php7.1-common' 'php7.1-curl' 'php7.1-dev' 'php7.1-fpm' 'php7.1-gd' 'php7.1-imap' 'php7.1-json' 'php7.1-mbstring' 'php7.1-mcrypt' 'php7.1-opcache' 'php7.1-sqlite3' 'php7.1-xml' 'Extracting templates from packages: 100%no' failed:
E: Sub-process /usr/bin/dpkg exited unexpectedly

PLAY RECAP ************************************************************************************************
127.0.0.1                  : ok=79   changed=1    unreachable=0    failed=1
`

**Comment by Careless** [comment]
i got a similar message just a few hours ago when the script tried to enable composer or something composer related (using raspian stretch with desktop only, none of the extra applications/packages), following the guide on the main git page.

Also, I seem to be having an issue connecting to RealVNC after running the install script. I have a feeling it has to do with fail2ban, but checking the jail entries does not produce any results, let alone any that even resemble the IP that I was trying to connect from.

Before running the script, it was working fine.

Is there any way to check something or upload a log file that may or may not help in trouble shooting this?

I can start a new issue/thread.

**Comment by geerlingguy** [comment]
So, I've decided to merge the Docker branch (see #36) into the master branch and tag it as version 3.0.0 of this project.

For now at least, I only plan on maintaining this project as Docker-based going forward, to make it more familiar for those considering switching between the single Pi and a Pi Dramble cluster.

It still uses Ansible to configure the Pi, and Nginx as a load balancer/reverse proxy, but Drupal and MySQL are run inside a Docker Compose-managed set of containers.
