### ISSUE TITLE
what am i doing wrong here? I can't get this to work at all

### ISSUE THREAD

**Issue by Careless** [geerlingguy/drupal-pi#35]
I configured the config file as per the instructions, and upon going to var/www there is only an HTML folder and it does not actually create a folder with my preferred name for the drupal installation.

nginx is running if I attempt to access the server from another computer via editing the hosts file to point to the RPi IP Address, and localhost works on the RPi itself and displays the nginx site, but there is no drupal to be found.

Is this package incompatible with Raspberry Pi Stretch?

I get errors too at the end of the installation on "ansible-playbook -i inventory -c local main.yml" command

```
fatal: [127.0.0.1]: FAILED! => {
    "changed": false
}

MSG:

Failed to connect to packages.sury.org at port 443: [Errno 101] Network is unreachable

```

**Comment by Careless** [comment]
it seems packages.sury.org is dead.
is this what is causing the main problem?

**Comment by Careless** [comment]
and as mentioned in my comment within the other issue thread, this script breaks RealVNC Viewer.

Upon completing the last main.yml playbook instruction and having it fail, I reboot the RPi, and RealVNC Viewer no longer connects to the RPi.

Attempting to reboot and connect BEFORE running the script works just fine. It's only after the script is run that the RealVNC Viewer no longer connects.

**Comment by geerlingguy** [comment]
It's possible that the Firewall rules added by `geerlingguy.firewall` are not allowing RealVNC to communicate over the VNC port(s).

You should override `firewall_allowed_tcp_ports` and set it to something like:

```yaml
firewall_allowed_tcp_ports:
  - 22
  - 80
  # For VNC.
  - 5900
  - 5800
```

For the Sury packages it could be something in this project needs updating.

**Comment by Careless** [comment]
will try the vnc ports.

as far as the project updating... how would I go about figuring out what needs updating- or is there a way of using the dramble version with a single RPi instead, since that seems like it gets more action.

**Comment by geerlingguy** [comment]
I kind of hop from one project to the other as I need to :D

Right now I'm actually working on a rewrite of this project to use Docker instead of running MySQL and PHP on the single Pi (instead they would run inside a container)... but that doesn't help if you can't get the existing `master` branch code working.

It's building in the CI environment, but I haven't run it on a physical Pi in a few months.

**Comment by geerlingguy** [comment]
Actually it seems packages.sury.org is alive and well, may have just been a temporary outage. I can build the normal config without an issue right now on a Pi... Going to close this and move further discussion back over to https://github.com/geerlingguy/drupal-pi/issues/33

I also have been testing a lot more on the `docker` branch (see issue #36), and am considering switching to that as the default branch, as it simplifies the playbook a bit, and also includes a few more testing options for me.

Plus it works with all the same images/defaults as my Pi Dramble Cluster... and allows me to use the Drupal Pi as a load balancer for the cluster, or as a standalone site, which is kinda awesome. No longer have to do router configuration updates to switch between the two!
