### ISSUE TITLE
docker-compose commands failing with "No module named shutil_get_terminal_size"

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-pi#42]
It seems like `docker-compose` is breaking on the default Python (2.7.x) under Raspbian Stretch...

```
TASK [Bring up the Docker containers.] *********************************************************************************
fatal: [10.0.100.10]: FAILED! => changed=true 
  cmd:
  - docker-compose
  - up
  - -d
  - --remove-orphans
  delta: '0:00:00.823091'
  end: '2019-11-27 17:51:51.533133'
  msg: non-zero return code
  rc: 1
  start: '2019-11-27 17:51:50.710042'
  stderr: |-
    Traceback (most recent call last):
      File "/usr/local/bin/docker-compose", line 6, in <module>
        from compose.cli.main import main
      File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 52, in <module>
        from .formatter import ConsoleWarningFormatter
      File "/usr/local/lib/python2.7/dist-packages/compose/cli/formatter.py", line 15, in <module>
        from backports.shutil_get_terminal_size import get_terminal_size
    ImportError: No module named shutil_get_terminal_size
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

I checked with `pip list installed` and `backports.shutil_get_terminal_size` is definitely installed (version 1.0.0).

**Comment by geerlingguy** [comment]
Easiest resolution might just be to force Python 3 / `pip3`:

```yaml
# Python configuration.
pip_package: python3-pip
pip_executable: pip3
```

**Comment by geerlingguy** [comment]
Also have to add `ansible_python_interpreter=/usr/bin/python3` to the inventory so the right interpreter is used for all the other commands (otherwise default `python` (2.7.x) is used).

**Comment by geerlingguy** [comment]
That seemed to work.

**Comment by felix-d-git** [comment]
> 
> 
> Easiest resolution might just be to force Python 3 / `pip3`:
> 
> ```yaml
> # Python configuration.
> pip_package: python3-pip
> pip_executable: pip3
> docker_pip_executable: '{{ pip_executable }}'
> ```

Where would I put that?

**Comment by jov58** [comment]
> 
> 
> > Easiest resolution might just be to force Python 3 / `pip3`:
> > ```yaml
> > # Python configuration.
> > pip_package: python3-pip
> > pip_executable: pip3
> > docker_pip_executable: '{{ pip_executable }}'
> > ```
> 
> Where would I put that?

Have you found where to put it and could you share that?

**Comment by geerlingguy** [comment]
@jov58 - That would go into your `config.yml` file.
