### ISSUE TITLE
Does drupal-pi disable SSH login?

### ISSUE THREAD

**Issue by nateswart** [geerlingguy/drupal-pi#8]
After running `ansible-playbook -i inventory -c local main.ml` and rebooting the Pi I am unable to SSH (even via IP) to the device.

If this is intentional, perhaps offer it as a configurable option and call it out in the install steps in  README.md?

**Comment by nateswart** [comment]
Not sure yet if it was drupal-pi that did this (though, I haven't done anything else on the pi other than this project), but I did find errors in my sshd config by running `sudo sshd -t. Fixing them allowed me to connect back in:

`sudo vi /etc/ssh/sshd_config'

There were 3 issues in the file:
1. `Could not load host key: /etc/ssh/ssh_host_ed25519_key` - I commented this line out (line 14)
2. `/etc/ssh/sshd_config line 28: unsupported option "False".` - I changed 'False' to 'no'
3. `/etc/ssh/sshd_config line 89: Bad yes/no argument: False` - I changed False to 'no'

**Comment by geerlingguy** [comment]
@nateswart - Ah, I think you ran into a bug that was present in the `geerlingguy.security` role with later versions of Ansible (which interpreted falsey vars differently than they used to be interpreted): https://github.com/geerlingguy/ansible-role-security/issues/7
